name: Sigma niga

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 300
    
    steps:
      - name: Downloading Essentials
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/chamod12/ngrok-win10-rdp/-/raw/main/Downloads.bat -OutFile Downloads.bat
          cmd /c Downloads.bat

      - name: Connecting sgma Account
        run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Enabling sigm Access
        run: cmd /c Acess.bat       

      - name: Log In To heck Protocol
        run: cmd /c startaudio.bat

      - name: Time Count
        run: cmd /c loop.bat
